# Quality Gates Configuration
gates:
  coverage:
    enabled: true
    threshold: 80

  maintainability:
    enabled: true
    threshold: B

  reliability:
    enabled: true
    threshold: A

  security:
    enabled: true
    threshold: A

  technical_debt:
    enabled: true
    max_ratio: 5

  code_smells:
    enabled: true
    max_count: 50

  bugs:
    enabled: true
    max_count: 0

  vulnerabilities:
    enabled: true
    max_count: 0

  duplication:
    enabled: true
    max_percent: 3

actions:
  on_failure:
    - notify_maintainers
    - block_merge
  on_warning:
    - create_issue